Repository TomRoush/PdfBox-Android, pull requests merged in 2021-03, with the labels that each got.

#244 Migrate from spongycastle to bouncycastle
  gradle.properties
  library/build.gradle
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/encryption/PublicKeySecurityHandler.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/encryption/SecurityHandlerFactory.java
  sample/src/main/java/com/tom_roush/pdfbox/sample/MainActivity.java
Labels: enhancement

#245 Update bouncycastle to the last version
  library/build.gradle
  library/src/main/java/com/tom_roush/pdfbox/exceptions/COSVisitorException.java
  library/src/main/java/com/tom_roush/pdfbox/multipdf/Overlay.java
  library/src/main/java/com/tom_roush/pdfbox/pdfparser/PDFObjectStreamParser.java
  library/src/main/java/com/tom_roush/pdfbox/pdfparser/PDFXrefStreamParser.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/PDDocument.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/PDPage.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/common/PDTextStream.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/encryption/PublicKeySecurityHandler.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/encryption/SecurityHandler.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/fdf/FDFAnnotation.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/fdf/FDFField.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/fdf/FDFJavaScript.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/font/PDCIDFontType2.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/font/PDFont.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/font/PDType3CharProc.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/graphics/form/PDFormXObject.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/graphics/pattern/PDTilingPattern.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/interactive/action/PDActionJavaScript.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/interactive/annotation/PDAnnotationMarkup.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/interactive/form/PDVariableText.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/interactive/form/PDXFA.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/interactive/form/PDXFAResource.java
Labels: enhancement

#246 Migrate from external to internal storage to fix tests
  library/src/androidTest/AndroidManifest.xml
  library/src/androidTest/java/com/tom_roush/pdfbox/encryption/TestSymmetricKeyEncryption.java
  library/src/androidTest/java/com/tom_roush/pdfbox/multipdf/PDFMergerUtilityTest.java
  library/src/androidTest/java/com/tom_roush/pdfbox/pdmodel/graphics/image/CCITTFactoryTest.java
  library/src/androidTest/java/com/tom_roush/pdfbox/pdmodel/graphics/image/JPEGFactoryTest.java
  library/src/androidTest/java/com/tom_roush/pdfbox/pdmodel/graphics/image/LosslessFactoryTest.java
  library/src/androidTest/java/com/tom_roush/pdfbox/pdmodel/graphics/image/PDInlineImageTest.java
  library/src/androidTest/java/com/tom_roush/pdfbox/pdmodel/interactive/form/AlignmentTest.java
  library/src/androidTest/java/com/tom_roush/pdfbox/pdmodel/interactive/form/MultilineFieldsTest.java
  sample/src/main/AndroidManifest.xml
  sample/src/main/java/com/tom_roush/pdfbox/sample/MainActivity.java
Labels: bug

#249 Bump Gradle plugin and junit versions
  build.gradle
  library/build.gradle
Labels: type: cleanup

#252 Fix unsupported class exception from BouncyCastle
  build.gradle
  gradle.properties
  library/build.gradle
Labels: type: bug

#253 Release v1.8.10.3
  README.md
  gradle.properties
  sample/build.gradle
Labels: type: release

#254 Travis CI cleanup
  .travis.yml
  gradle.properties
Labels: type: cleanup

#255 Fix a NPE on PDFStreamEngine. Fix a leak on FlateFilter
  library/src/main/java/com/tom_roush/pdfbox/contentstream/PDFStreamEngine.java
  library/src/main/java/com/tom_roush/pdfbox/filter/FlateFilter.java
Labels: type: bug
