Repository TomRoush/PdfBox-Android, pull requests merged in 2022-05, with the labels that each got.

#400 Version bump to 2.0.21.0-SNAPSHOT
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  gradle.properties
Labels: type: api-upgrade

#405 Version bump to 2.0.22.0-SNAPSHOT
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  gradle.properties
Labels: type: release

#406 Add proguard rules.
  library/build.gradle
  library/consumer-proguard-rules.txt
Labels: type: enhancement

#413 Version bump to 2.0.23.0-SNAPSHOT
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  gradle.properties
Labels: type: release
