Repository TomRoush/PdfBox-Android, pull requests merged in 2022-03, with the labels that each got.

#377 Version bump to 2.0.17.0-SNAPSHOT
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  gradle.properties
Labels: type: release

#380 fix PDImageXObject read red image as black for some soft mask images
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/graphics/image/PDImageXObject.java
Labels: type: bug

#381 Version bump to 2.0.18.0-SNAPSHOT
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  gradle.properties
Labels: type: release

#386 replace `getPixel` with `getPixels`, which makes it 10 times faster
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/graphics/color/PDDeviceGray.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/graphics/image/CCITTFactory.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/graphics/image/PDImageXObject.java
Labels: type: enhancement

#387 add support for jpx decode/encode with JP2ForAndroid
  build.gradle
  library/build.gradle
  library/src/main/java/com/tom_roush/pdfbox/filter/DecodeResult.java
  library/src/main/java/com/tom_roush/pdfbox/filter/FilterFactory.java
  library/src/main/java/com/tom_roush/pdfbox/filter/JPXFilter.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/graphics/color/PDJPXColorSpace.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/graphics/image/PDImageXObject.java
  library/src/test/java/com/tom_roush/pdfbox/filter/TestFilters.java
Labels: type: enhancement

#391 Document JPX support, make JP2Android library optional
  README.md
  library/build.gradle
  library/src/main/java/com/tom_roush/pdfbox/filter/JPXFilter.java
  library/src/main/java/com/tom_roush/pdfbox/io/IOUtils.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/graphics/color/PDJPXColorSpace.java
  library/src/main/java/com/tom_roush/pdfbox/pdmodel/graphics/image/PDImageXObject.java
  sample/build.gradle
Labels: type: enhancement
